# Copyright (c) 2016-2020 Dell Inc. or its subsidiaries.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

resource_registry:
  OS::TripleO::Network::Ports::StorageMgmtVipPort: ./overcloud/network/ports/ctlplane_vip.yaml
  OS::TripleO::Controller::Ports::StorageMgmtPort: ./overcloud/network/ports/noop.yaml


parameter_defaults:
  # CHANGEME: Change the following to the desired MTU for Neutron Networks
  NeutronGlobalPhysnetMtu: {{NeutronGlobalPhysnetMtu}}
  # CHANGEME: Change the following to the CIDR for the Management network
  ManagementNetCidr: {{ManagementNetCidr}}

  # CHANGEME: Change the following to the CIDR for the Private API network
  InternalApiNetCidr: {{InternalApiNetCidr}}

  # CHANGEME: Change the following to the CIDR for the Tenant network
  TenantNetCidr: {{TenantNetCidr}}

  # CHANGEME: Change the following to the CIDR for the Storage network
  StorageNetCidr: {{StorageNetCidr}}

  # CHANGEME: Change the following to the CIDR for the Storage Clustering network
  StorageMgmtNetCidr: {{StorageMgmtNetCidr}}

  # CHANGEME: Change the following to the CIDR for the External network
  ExternalNetCidr: {{ExternalNetCidr}}

  # CHANGEME: Change the following to the DHCP ranges for the iDRACs to use on
  # the Management network
  ManagementAllocationPools: {{ManagementAllocationPools}}

  # The allocation pools below are used to dynamically assign DHCP IP addresses
  # to the various networks on the overcloud nodes as they are provisioned.  If
  # using static IPs instead, see static-ip-environment.yaml.

  # CHANGEME: Change the following to the DHCP range to use on the
  # Private API network
  InternalApiAllocationPools: {{InternalApiAllocationPools}}

  # CHANGEME: Change the following to the DHCP range to use on the
  # Tenant network
  TenantAllocationPools: {{TenantAllocationPools}}

  # CHANGEME: Change the following to the DHCP range to use on the
  # Storage network
  StorageAllocationPools: {{StorageAllocationPools}}

  # CHANGEME: Change the following to the DHCP range to use on the
  # Storage Clustering network
  StorageMgmtAllocationPools: {{StorageMgmtAllocationPools}}

  # CHANGEME: Change the following to the DHCP range to use on the
  # External network
  ExternalAllocationPools: {{ExternalAllocationPools}}

  # CHANGEME: Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: {{ExternalInterfaceDefaultRoute}}

  # CHANGEME: Set to the router gateway on the management network
  ManagementNetworkGateway: {{ManagementNetworkGateway}}

  # CHANGEME: Set to the IP of the gateway on the provisioning network which
  # will allow access to the management network
  ProvisioningNetworkGateway: {{ProvisioningNetworkGateway}}

  # CHANGEME: Set to the router gateway on the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: {{ControlPlaneDefaultRoute}}

  # CHANGEME: Set to the CIDR of the control plane network
  ControlPlaneSubnetCidr: {{ControlPlaneSubnetCidr}}

  # CHANGEME: Set to the network/cidr of the control plane network
  ControlPlaneNetCidr: {{ControlPlaneNetCidr}}

  # CHANGEME: Set to the IP address of the Undercloud
  EC2MetadataIp: {{EC2MetadataIp}}

  # CHANGEME: Set to the DNS servers to use for the overcloud nodes (maximum 2)
  DnsServers: {{DnsServers}}

  # CHANGEME: Change the following to the VLAN ID to use on the
  # Private API network
  InternalApiNetworkVlanID: {{InternalApiNetworkVlanID}}

  # CHANGEME: Change the following to the VLAN ID to use on the
  # Storage network
  StorageNetworkVlanID: {{StorageNetworkVlanID}}

  # CHANGEME: Change the following to the VLAN ID to use on the
  # Storage Clustering network
  StorageMgmtNetworkVlanID: {{StorageMgmtNetworkVlanID}}

  # CHANGEME: Change the following to the VLAN ID to use on the
  # Tenant network
  TenantNetworkVlanID: {{TenantNetworkVlanID}}

  # CHANGEME: Change the following to the VLAN ID to use on the
  # External network
  ExternalNetworkVlanID: {{ExternalNetworkVlanID}}
  # CHANGEME: Change the following to the MTU value to use on the
  # External network
  ExternalMtu: {{ExternalMtu}}
  # CHANGEME: Change the following to the MTU value to use on the
  # internal network
  InternalApiMtu: {{InternalApiMtu}}
  # CHANGEME: Change the following to the MTU value to use on the
  # Storage network
  StorageMtu: {{StorageMtu}}
  # CHANGEME: Change the following to the MTU value to use on the
  # StorageMgmtNetwork network
  StorageMgmtMtu: {{StorageMgmtMtu}}
  # CHANGEME: Change the following to the MTU value to use on the
  # TenantNetwork network
  TenantMtu: {{TenantMtu}}
  # CHANGEME: Change the following to the MTU value to use on the
  # Provisioning network
  ProvisioningMtu: {{ProvisioningMtu}}
  # CHANGEME: Change the following to the MTU value to use on the
  # Management network
  ManagementMtu: {{ManagementMtu}}
  # CHANGEME: Change the following to the MTU value to use on the
  # Default Bonds MTU
  DefaultBondMtu: {{DefaultBondMtu}}

{%- for network in edge_networks %}
  {{network}}
{%- endfor %}
  # CHANGEME: Change the following to mtu size used for the floating network
  ExtraConfig:
    neutron::plugins::ml2::physical_network_mtus: {{neutron_plugins_ml2_physical_network_mtus}}
  # CHANGEME: Set to empty string for External VLAN, br-ex if on native VLAN of br-ex
  NeutronExternalNetworkBridge: "''"
  ServiceNetMap:
    NeutronTenantNetwork: tenant
    CeilometerApiNetwork: internal_api
    AodhApiNetwork: internal_api
    GnocchiApiNetwork: internal_api
    MongoDbNetwork: internal_api
    CinderApiNetwork: internal_api
    CinderIscsiNetwork: storage
    GlanceApiNetwork: storage
    GlanceRegistryNetwork: internal_api
    KeystoneAdminApiNetwork: ctlplane # allows undercloud to config endpoints
    KeystonePublicApiNetwork: internal_api
    NeutronApiNetwork: internal_api
    HeatApiNetwork: internal_api
    NovaApiNetwork: internal_api
    NovaMetadataNetwork: internal_api
    NovaVncProxyNetwork: internal_api
    SwiftMgmtNetwork: storage # Changed from storage_mgmt
    SwiftProxyNetwork: storage
    SaharaApiNetwork: internal_api
    HorizonNetwork: internal_api
    MemcachedNetwork: internal_api
    RabbitMqNetwork: internal_api
    RedisNetwork: internal_api
    MysqlNetwork: internal_api
    CephClusterNetwork: storage_mgmt
    CephPublicNetwork: storage
    CephRgwNetwork: storage
    ControllerHostnameResolveNetwork: internal_api
    ComputeHostnameResolveNetwork: internal_api
    BlockStorageHostnameResolveNetwork: internal_api
    ObjectStorageHostnameResolveNetwork: internal_api
    CephStorageHostnameResolveNetwork: storage
    NovaColdMigrationNetwork: internal_api
    NovaLibvirtNetwork: internal_api
