
parameter_defaults:
  NovaComputeAvailabilityZone: {{az}}
  ControllerExtraConfig:
    nova::availability_zone::default_schedule_zone: {{az}}
  NovaCrossAZAttach: false
  CinderStorageAvailabilityZone: {{az}}
  GlanceBackendID: {{az}}
